Feature/transcoder factory
ngraveio/bc-ur pull request #16
Opened 2023-04-17 08:27 UTC by Pietahr

2023-04-17 15:13 UTC, irfan798 requested changes
I will continue to review,

One major issue we need to address is the usage of `Buffer` class. That is only usable in nodejs environment, not browser.

We may need to check if we are in a browser and change it. Or use a package that works both in browser and nodejs.

2023-04-17 15:13 UTC, irfan798 commented on src/classes/UrFountainEncoder.ts
> +    minFragmentLength: number = 10,
We need to change these to the calculated numbers for QR codes

2023-04-17 15:13 UTC, irfan798 commented on src/classes/UrFountainDecoder.ts
> +      // that `this.processedPartsCount` also tracks the duplicate parts that have been
So lets not track duplicate parts

2023-04-17 15:13 UTC, irfan798 commented on src/classes/UrFountainDecoder.ts
> +    receivePart(s: string): boolean {
We should also keep track if we are reading the same multipart QR by looking at total and current fragment number and type

2023-04-18 12:09 UTC, Pietahr commented on src/interfaces/RegistryType.ts
> +    type: string;
Registry type is what defines it in the UR registry. the 'type' which is the name, and the 'tag' which is the id.

e.g:
`{
type: "bytes",
tag: 0
}`

We currently do not use the 'tag'. So not sure to add this interface, or only keep using the "type". That one is used in the bc-ur string and is encoded in the payload for verification.

2023-04-18 12:17 UTC, Pietahr commented on src/enums/EncodingMethodName.ts
> +  }
My idea was to provide our implementation as the default one in the package. But leave the ability open for consumers of the package to create their own Transcoders by extending the interfaces and let them create their own EncodingMethods, or choose one we have created.
For this case, we can change the IEncodingMethod to accept a string as well. 

```
export interface IEncodingMethod<T, U> {
    name: EncodingMethodName | string ;
    // has another encoding method that encodes the output value of this one.
    encodingMethod?: IEncodingMethod<U, any>;
    encode(payload: T): U;
    decode(payload: U): T;
  }
```

We can also choose to keep the package limited to our implementation, which will be easier to maintain, but less customisable. and thus only accepting this enum.

2023-04-18 12:36 UTC, Pietahr commented on src/classes/HexEncoding.ts
> +        return Buffer.from(payload, "hex");
Right now it just decodes the string as if it is a hex. I added 2 tests to check these cases.

We could add a regex test before we decode checking this case if that is required.

2023-04-18 12:39 UTC, Pietahr commented on src/classes/Ur.ts
> +   * Checks if the given type is a valid UR type (consisting of lowercase letters, numbers or dashes)
This only checks the 'type', which is only a part of the ur string.

`ur:bytes/1-9/lpadascfadaxcywenbpljkhdcahkadaemejtswhhylkepmykhhtsytsnoyoyaxaedsuttydmmhhpktpmsrjtdkgslpgh`

"bytes" in this case.

2023-04-18 12:40 UTC, Pietahr commented on src/classes/Ur.ts
> +   * @param scheme scheme of the uri. e.g. "ur"
first is the param name, second is the start of the description of the property.

2023-04-18 12:40 UTC, Pietahr commented on src/classes/Ur.ts
> +  static encodeUR(pathComponents: string[]): string {
agreed!

2023-04-18 12:44 UTC, Pietahr commented on src/classes/Ur.ts
> +    assert(typeof type === 'string', "registry type should be included in the ur payload");
this is the case. For example inside "decodeFragments", we use "decodeMultipartUr", which splits up the ur string and takes the type from there.

2023-04-18 12:47 UTC, Pietahr commented on src/classes/UrEncoder.ts
> +  getFragment(ur: Ur): string {
Fair point. I renamed it to "encodeUr"

2023-04-18 12:51 UTC, Pietahr commented on src/classes/UrEncoder.ts
> +    const cborMessage = this.cborEncode(ur);
it encodes the cbor with cbor. But does the same when decoding, so the original cbor will be returned after decoding.

2023-04-18 12:53 UTC, Pietahr commented on src/classes/UrEncoder.ts
> +    return _fragments;
what? 😛

2023-04-18 13:02 UTC, Pietahr commented on src/classes/UrDecoder.ts
> +    return this._encodingMethods[this._encodingMethods.length - 1].decode(
Indeed. We can filter the _encodingMethods by name?

2023-04-18 13:04 UTC, Pietahr commented on src/classes/UrDecoder.ts
> +    const [seqNum, seqLength, messageLength, checksum, fragment] = decoded;
"decoded" is the decoded cbor buffer for a multipart ur. It is a buffer array that has this order. (we encode it like this ourselves)

2023-04-18 13:06 UTC, Pietahr commented on src/classes/UrDecoder.ts
> +    return [type, components.slice(1)];
correct. we copy the array starting from index 1

2023-04-18 13:06 UTC, Pietahr commented on src/classes/UrFountainEncoder.ts
> +    minFragmentLength: number = 10,
what do you mean by "the calculated numbers for QR codes"?

2023-04-18 13:15 UTC, Pietahr commented on src/classes/UrFountainDecoder.ts
> +      // that `this.processedPartsCount` also tracks the duplicate parts that have been
Honestly do not want to focus on the progress part yet. This is not my comment.

2023-04-18 13:16 UTC, Pietahr commented on src/classes/UrFountainDecoder.ts
> +    receivePart(s: string): boolean {
why?

2023-04-21 07:10 UTC, MahammadNuriyev62 commented on src/classes/UrEncoder.ts
> +    const cborMessage = this.cborEncode(ur);
In this case you can use any other `cbor encode/decode` right? For example your own, not the one provided by user in `_encodingMethods`

2023-04-21 07:10 UTC, MahammadNuriyev62 commented on src/classes/UrEncoder.ts
> +   * get an array of encoded fragments, based on the payload length, max en min fragment length.
`en`

2023-04-21 07:10 UTC, MahammadNuriyev62 commented on src/classes/UrEncoder.ts
> +   * @returns the encoded payload as am array of ur strings
`am`

2023-04-21 07:10 UTC, MahammadNuriyev62 commented on src/classes/UrEncoder.ts
> +    redundancyRatio: number = 0
i believe min value of redundancy is 1, which means no extra(redundant) frames

2023-04-21 07:10 UTC, MahammadNuriyev62 commented on src/classes/UrEncoder.ts
> +    const numberofParts = Math.ceil(fragments.length * (1 + redundancyRatio));
from previous comment, `1 + redundancyRatio` becomes `redundancyRatio`

2023-04-21 07:10 UTC, MahammadNuriyev62 commented on src/classes/UrEncoder.ts
> +    return _fragments;
.

2023-04-21 07:10 UTC, MahammadNuriyev62 commented on src/classes/UrEncoder.ts
> +    let _fragments: Buffer[] = [];
why do you have this ugly `_` in `_fragments`?

2023-04-24 15:03 UTC, MahammadNuriyev62 commented on tests/hexEncoding.test.ts
> +
you could add test case checking that `input = decode(encode(input))`

2023-04-25 14:19 UTC, Pietahr commented on src/classes/UrEncoder.ts
> +    const cborMessage = this.cborEncode(ur);
Correct, it uses the encoding method provided in _encodingMethods

2023-04-25 14:21 UTC, Pietahr commented on src/classes/UrDecoder.ts
> +    return this._encodingMethods[this._encodingMethods.length - 1].decode(
yes, this is a valid solution as well if we keep the close relationship between ur and cbor!

2023-04-25 14:26 UTC, Pietahr commented on src/classes/Encoder.ts
> +  _encodingMethods: IEncodingMethod<any, any>[];
declared the "_" one as private and created a getter for it, so it can only be changed in the constructor.

2023-04-25 14:42 UTC, Pietahr commented on src/classes/Ur.ts
> +    return getUrString(this.type, this.payload);
you are right, I removed it because it was not used anyway

2023-04-25 14:48 UTC, Pietahr commented on src/classes/UrDecoder.ts
> +   * @param fragments array of stringified Ur's, in the correct order.
updated docs

2023-04-25 15:27 UTC, Pietahr commented on src/classes/UrEncoder.ts
> +    redundancyRatio: number = 0
the way it is implemented now, 0 means no extra frames. You can check the tests. I added an extra one especially for you ;)

2023-04-25 15:33 UTC, Pietahr commented on src/classes/UrFountainEncoder.ts
> +    firstSeqNum: number = 0,
You can choose to skip a number of fragments by passing a number here. if you pass in 100. you will start with the 100th generated frame.

2023-04-25 15:35 UTC, Pietahr commented on src/fountainUtils.ts
>    if (seqNum <= seqLength) {
then it will always create an array of shuffled indexes, that will be used to create a mixed fragment later on.

2023-04-25 15:42 UTC, Pietahr commented on tests/hexEncoding.test.ts
> +
et voila.

2024-09-04 12:34 UTC, Pietahr commented on src/classes/UrFountainDecoder.ts
> +    receivePart(s: string): boolean {
this is done, look at the tests under section "Passing wrong encoded data into the FountainDecoder"

2024-09-09 15:34 UTC, irfan798 approved these changes

2024-09-09 15:35 UTC, merged