feat: updated all dependencies and switched cbor package
ngraveio/bc-ur pull request #26
Opened 2024-10-02 14:36 UTC by Pietahr

2024-10-18 13:57 UTC, irfan798 requested changes
Just 2 issue related to export of cbor and tests, can you check them?

2024-10-18 13:57 UTC, irfan798 commented on src/encodingMethods/cbor.ts
>  };
Why export encode function as default?

Maybe you can export the cbor package as default?
So for low level it can be used.

2024-10-18 13:57 UTC, irfan798 commented on tests/UrMultipartTranscoder.test.ts
> +    // test("Should throw an error when a multipart payload is not validated correctly", () => {
Is this not working anymore?

2024-10-21 07:20 UTC, Pietahr commented on src/encodingMethods/cbor.ts
>  };
I don't really remember, I think it was already the case. But I have applied your suggestion.

2024-10-21 08:45 UTC, merged