feat: create test and release pipelines
ngraveio/bc-ur pull request #28
Opened 2024-10-07 16:44 UTC by Spikatrix

2024-10-15 14:44 UTC, Spikatrix commented on package.json
> -    "prepublish": "yarn build",
The `prepublish` script gets run whenever `yarn`/`yarn install`/`yarn add` is executed which was annoying. IMO, running install shouldn't trigger a build.
Upstream issue: https://github.com/yarnpkg/yarn/issues/3209

2024-10-15 14:47 UTC, Spikatrix commented on .github/workflows/release.yml
> +        run: npx semantic-release
It's configured with the [`.releaserc`](https://github.com/ngraveio/bc-ur/blob/0ddf25213ce0ddfbf52159a96f28a9163b15235f/.releaserc) file. Currently, I have it set to deploy beta releases from the development branch and stable releases from the main/master branch but I'll modify it to use main for beta and release for stable

2024-10-16 08:49 UTC, irfan798 requested changes

2024-10-16 08:49 UTC, irfan798 commented on .github/workflows/sync-main-branch.yml
>        - main
On push to release

2024-10-16 08:50 UTC, merged