feat: static from
ngraveio/bc-ur pull request #3
Opened 2021-03-15 17:36 UTC by AndreasGassmann

When building this library with browserify, the Buffer module is bundled internally. To avoid duplicating the code, it would be nice to have a method that will take any input and convert it to a buffer.

2021-03-16 09:05 UTC, antonispoulakis requested changes

2021-03-16 09:05 UTC, antonispoulakis commented on src/ur.ts
> +    return UR.fromBuffer(Buffer.from(value));
This will not work for strings not encoded in `utf-8`, as `Buffer.from` needs the encoding as a second param. 
Adding it as an optional second param will fix that.
```suggestion
  public static from(value: any, encoding?: string) {
    return UR.fromBuffer(Buffer.from(value, encoding));
```

2021-03-16 09:58 UTC, AndreasGassmann commented
I added the encoding parameter.

2021-06-26 15:44 UTC, antonispoulakis approved these changes

2021-06-26 15:44 UTC, merged