Cbor2
ngraveio/bc-ur pull request #30
Opened 2024-11-08 15:10 UTC by irfan798

2024-11-08 16:44 UTC, Pietahr requested changes
Nice docs

2024-11-08 16:44 UTC, Pietahr commented on src/classes/CryptoPortfolioMetadata.ts
> +//  * "fr" for French, "nl" for Dutch and "es" for Spanish
we can delete

2024-11-08 16:44 UTC, Pietahr commented on src/classes/LanguageCodes.ts
> +      "family": "Northwest Caucasian",
We can delete

2024-11-08 16:44 UTC, Pietahr commented on src/classes/RegistryItem.ts
> +  keyMap?: IKeyMap;
would be good to have the docs for these props too. Just starting to review this. The 'URType" prop is not really clear to me

2024-11-08 16:44 UTC, Pietahr commented on src/classes/RegistryItem.ts
> +  /** If CDDL contains keys as numbers, map them to their respective values */
👍

2024-11-08 16:44 UTC, Pietahr commented on src/classes/RegistryItem.ts
> +  keyMap?: IKeyMap;
so it's the name of the top level ur Registry item?

2024-11-08 16:44 UTC, Pietahr commented on src/encodingMethods/CborEncoding.ts
> +   * @param enforceType @type RegistryItemClass
I would explain `enforceType` more extensively

2024-11-08 16:44 UTC, Pietahr commented on src/ngraveTranscoder.ts
> +    // TODO: check if we can add key-map converter here
we can't and we do not need to anymore, so you can remove the comment

2024-11-08 16:44 UTC, Pietahr commented on src/registry.ts
> +// Make sure CBOR2 tag registry is updated
another ticket to create 👆

2024-11-08 16:44 UTC, Pietahr commented on src/types/cbor2/box.d.ts
> + * @param obj Object to check.
used for development, can be removed?

2024-11-08 16:44 UTC, Pietahr commented on src/types/cbor2/options-QQFLweAY.d.ts
used for development, can be removed?

2024-11-08 16:44 UTC, Pietahr commented on tests/NgraveTranscoder.test.ts
> +import { CryptoPortfolioMetadata } from "../src/classes/CryptoPortfolioMetadata";
can be removed or that example needs to be migrated to the tests

2024-11-08 16:44 UTC, Pietahr commented on tests/cbor.test.ts
> +        let reasons: Error[] = [];
you could put all this stuff in a helper function outside the test file. the tests will be shorter and it will be easier to use it as a reference to create custom registryItems

2024-11-08 16:44 UTC, Pietahr commented on tests/cbor.test.ts
> +      CborEncoding.addToRegistry(UserCollection);
And just import them from the other file here

2024-11-08 16:44 UTC, Pietahr commented on tests/cbor.test.ts
> +  describe("Advanced Registry Items", () => {
Custom registry items. I would add a separate test file for this.

2024-11-08 16:44 UTC, Pietahr commented on tests/cbor.test.ts
> +        expect(encoded.toString("hex")).toEqual("d86fa262696401646e616d6571c4b07266616e2042696c616c6fc49f6c75");
add as a var `userEncoded = "d86fa262696401646e616d6571c4b07266616e2042696c616c6fc49f6c75"`

2024-11-08 16:44 UTC, Pietahr commented on tests/cbor.test.ts
> +        const encoded = Buffer.from("d86fa262696401646e616d6571c4b07266616e2042696c616c6fc49f6c75", "hex");
userEncoded

2024-11-08 16:44 UTC, Pietahr commented on tests/cbor.test.ts
> +      // TODO:
remove

2024-11-08 16:44 UTC, Pietahr commented on tests/cbor.test.ts
> +      });
I don't get this test

2024-11-08 16:44 UTC, Pietahr commented on tests/cbor.test.ts
> +        const encoded = Buffer.from("d86fa262696401646e616d6571c4b07266616e2042696c616c6fc49f6c75", "hex");
userEncoded

2024-11-08 16:44 UTC, Pietahr commented on src/encodingMethods/CborEncoding.ts
> +    cborLibOptions?: DecodeOptions
can we extend the DecodeOptions with `enforceType`, then we can group it under 1 property and pass it like this 
`decode(payload, {enforceType: "aType"})`

2024-11-08 16:44 UTC, Pietahr commented on tests/cbor.test.ts
> +      it("should decode to correct RegistryItem if its already that class and enforced type is given", () => {
should decode to the correct RegistryItem when it's already that class and additionally the enforced type is given

2024-11-08 16:44 UTC, Pietahr commented on tests/cbor.test.ts
> +    describe("Registry Item with Registry Item children", () => {
Embedding Registry Items

2024-11-08 16:44 UTC, Pietahr commented on tests/cbor.test.ts
> +      const user2 = new User({ id: 2, name: "Pieter Uyttersprot" });
😎

2024-11-08 16:44 UTC, Pietahr commented on tests/cbor.test.ts
> +        expect(encoded.toString("hex")).toEqual("d870a2646e616d656d4d7920436f6c6c656374696f6e65757365727382d86fa262696401646e616d6571c4b07266616e2042696c616c6fc49f6c75d86fa262696402646e616d6572506965
`userCollectionEncoded = "d870a2646e616d656d4d7920436f6c6c656374696f6e65757365727382d86fa262696401646e616d6571c4b07266616e2042696c616c6fc49f6c75d86fa262696402646e616d6572506965746572205579747465727370726f74"`

2024-11-08 16:44 UTC, Pietahr commented on tests/cbor.test.ts
> +    describe("Decode with enforced type", () => {
So you need to enforce a type when the top level registryItem is not a Tag?

2024-11-08 16:44 UTC, Pietahr commented on tests/cbor.test.ts
> +  describe("Registry Items with KeyMap", () => {
Move to a separate file

2024-11-08 16:44 UTC, Pietahr commented on tests/cbor.test.ts
> +    it("should convert string keys into integers on cbor encoded", () => {
should convert string keys into integers in cbor encoded data

2024-11-08 16:44 UTC, Pietahr commented on tests/cbor.test.ts
> +    it("should encode and decode with same data re converting the keys", () => {
should encode and decode with same the same data, having the orginal keys

2024-11-08 16:44 UTC, Pietahr commented on tests/registryItem.test.ts
> +  it("should define an registry item class that has static properties", () => {
should define **a** registry item class

2024-11-25 10:35 UTC, irfan798 commented on src/classes/RegistryItem.ts
> +      // TODO: add ability to ignore the keys that are not in keymap
https://gitlab.com/ngrave/ngrave-liquid/liquid-backend/liquid-backend/-/issues/1338

2024-11-25 10:39 UTC, irfan798 commented on src/encodingMethods/CborEncoding.ts
> +    // TODO: For web compatibility, we need to convert Buffer to Uint8Array
https://gitlab.com/ngrave/ngrave-liquid/liquid-backend/liquid-backend/-/issues/1328
https://gitlab.com/ngrave/ngrave-liquid/liquid-backend/liquid-backend/-/issues/1339

2024-11-25 11:24 UTC, irfan798 commented on src/encodingMethods/CborEncoding.ts
> +    cborLibOptions?: DecodeOptions
No, enforced type is better of with staying individual but i will check the decode options object when I implement the isolated registry

2024-11-25 11:26 UTC, irfan798 commented on tests/NgraveTranscoder.test.ts
> +import { CryptoPortfolioMetadata } from "../src/classes/CryptoPortfolioMetadata";
It can be removed but we need to convert these tests

2024-11-25 11:32 UTC, irfan798 commented on tests/cbor.test.ts
> +      });
Its a normal cbor encoded data, just an object

So if it doesnt have a tag and and if we dont enforce it, it should just return regular javascript object

2024-11-25 11:36 UTC, irfan798 commented on src/classes/RegistryItem.ts
> +  keyMap?: IKeyMap;
yes

2024-11-28 14:04 UTC, merged